const List<Map<String, dynamic>> sampleProducts = [
  {
    "uid": "1",
    "name": "특 샤인머스켓 2kg",
    "image": "assets/thumbnail/shine.jpg",
    "price": 2000,
    "discount_rate": 10,
    "original_price": 2200,
    "main_category": "농산물",
    "sub_category": "과실류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "2",
    "name": "사과 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "농산물",
    "sub_category": "과실류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "3",
    "name": "상추 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "농산물",
    "sub_category": "채소류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "4",
    "name": "쌀 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "농산물",
    "sub_category": "곡류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "5",
    "name": "감자 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "농산물",
    "sub_category": "서류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "6",
    "name": "느타리버섯 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "농산물",
    "sub_category": "버섯류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "7",
    "name": "고등어 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "수산물",
    "sub_category": "어류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "8",
    "name": "전복 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "수산물",
    "sub_category": "패류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "9",
    "name": "꽃게 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "수산물",
    "sub_category": "갑각류",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "10",
    "name": "등심 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "축산물",
    "sub_category": "소고기",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "11",
    "name": "삼겹살 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "축산물",
    "sub_category": "돼지고기",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "12",
    "name": "토종닭 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "축산물",
    "sub_category": "닭고기",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "13",
    "name": "전복장 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "가공식품",
    "sub_category": "조리식품",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "14",
    "name": "꽁치캔 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "가공식품",
    "sub_category": "통조림",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "15",
    "name": "장조림 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "반찬가게",
    "sub_category": "반찬",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
  {
    "uid": "16",
    "name": "김치 5kg",
    "image": "assets/thumbnail/apple.jpg",
    "price": 1500,
    "discount_rate": 5,
    "original_price": 1580,
    "main_category": "반찬가게",
    "sub_category": "김치",
    'details': [
      {'key': '제조사', 'value': '샘플 제조사'},
      {'key': '원산지', 'value': '샘플 원산지'},
      {'key': '유통기한', 'value': '샘플 유통기한'},
      {'key': '보관방법', 'value': '샘플 보관방법'},
    ],
  },
];
