// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAG4HD7sJFrOe1NdY2kS2kNr8PsLSE9bWI',
    appId: '1:712542314773:web:079b1b0a357fb91bf7c91c',
    messagingSenderId: '712542314773',
    projectId: 'v3mvp-b9aa4',
    authDomain: 'v3mvp-b9aa4.firebaseapp.com',
    storageBucket: 'v3mvp-b9aa4.appspot.com',
    measurementId: 'G-05P3C342ZY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkYaLi_r-As5Mo8b0mbl_RNBBYI4SU-bc',
    appId: '1:712542314773:android:ed5755798eaa5a48f7c91c',
    messagingSenderId: '712542314773',
    projectId: 'v3mvp-b9aa4',
    storageBucket: 'v3mvp-b9aa4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDIiOinZaTzt3iu6zhWP8z_hyR1173Fh6k',
    appId: '1:712542314773:ios:bcdd897c338b7818f7c91c',
    messagingSenderId: '712542314773',
    projectId: 'v3mvp-b9aa4',
    storageBucket: 'v3mvp-b9aa4.appspot.com',
    iosBundleId: 'com.bgood.v3Mvp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDIiOinZaTzt3iu6zhWP8z_hyR1173Fh6k',
    appId: '1:712542314773:ios:40781c46bd76e349f7c91c',
    messagingSenderId: '712542314773',
    projectId: 'v3mvp-b9aa4',
    storageBucket: 'v3mvp-b9aa4.appspot.com',
    iosBundleId: 'com.bgood.v3Mvp.RunnerTests',
  );
}
